---
# https://wiki.alpinelinux.org/wiki/Securing_Alpine_Linux
# install and configure fail2ban
- name: Ensure fail2ban is installed
  community.general.apk:
    name: fail2ban
    state: present
  when: ansible_facts['os_family'] == "Alpine"
  tags: always

- name: Ensure fail2ban is enabled and started
  ansible.builtin.service:
    name: fail2ban
    enabled: yes
    state: started
  tags: always

# https://wiki.alpinelinux.org/wiki/Fail2ban
- name: Ensure default alpine ssh jails are configured
  ansible.builtin.template:
    src: templates/alpine-ssh.conf.j2
    dest: /etc/fail2ban/jail.d/alpine-ssh.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart fail2ban
  tags: always

- name: Ensure sshd-key jail is configured
  ansible.builtin.copy:
    src: files/alpine-sshd-key.conf
    dest: /etc/fail2ban/filter.d/alpine-sshd-key.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart fail2ban
  tags: always 
